# Generated by Django 2.1.5 on 2019-02-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='mobile',
            field=models.CharField(max_length=12),
        ),
    ]
